version: '3.8'

services:
  medhistoryapp:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - postgres
    networks:
      - medhistoryapp-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=medhistoryapp
      - POSTGRES_USER=meduser
      - POSTGRES_PASSWORD=medpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - medhistoryapp-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  medhistoryapp-network:
    driver: bridge