services:
  - type: web
    name: medhistoryapp
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromSecret: database_url
      - key: JWT_SECRET
        fromSecret: jwt_secret
      - key: GROQ_API_KEY
        fromSecret: groq_api_key
      - key: PORT
        value: 10000